GET http://127.0.0.1:5000/tarefas


###

POST http://127.0.0.1:5000/tarefas
Content-Type: application/json

{
    "titulo": "Estudar Python",
    "feita": 0
}


###

POST http://127.0.0.1:5000/tarefas
Content-Type: application/json

{
    "titulo": "Fazer trabalho",
    "feita": 0
}


###

GET http://127.0.0.1:5000/tarefas


###

PUT http://127.0.0.1:5000/tarefas/1
Content-Type: application/json

{
    "titulo": "Estudar Python e Flask",
    "feita": 1
}


###

GET http://127.0.0.1:5000/tarefas


###

DELETE http://127.0.0.1:5000/tarefas/2


###

GET http://127.0.0.1:5000/tarefas